### PR TITLE
Added netstandard2.0 compatibility and various small fixes

### PR DESCRIPTION
**Pull request by peterdeme**
Hi Team,

I did not modify any functionality just enhanced the usage of some. So there is no public API change at all. But not having netstandard2.0 is a blocker for my company currently.

Changelist:

- Fixed TargetFrameworks - it should never have been `netcoreapp`. `netcoreapp` is used for applications not libraries.
- Added netstandard2.0 compatibility by adding `netstandard2.0` in the targetframeworks.
- Using strongly typed http method (`System.Net.Http.HttpMethod`) instead of weakly typed (`string`)
- Fixed the using of `string` instead of `String` across the solution as this is the de-facto standard in C#
- Fixed WebhookParser class where `VerifySignature` was invoked in the constructor which is a bad thing (constructors should **not** do hard work or throw exceptions), moved it to Parse method
- Removed `Joiner` class as it was internal but wasn't used anywhere in the code
- Removed empty spaces/tabs from various classes, added empty lines before some `return` statements though
- Disposing `HMACSHA256` after usage, disposing `HttpRequestMessage` after usage
- 3 minor things in `README.md` -> don't need to specify NuGet version to install the latest one, consistent use of `var`, consistent use of `string` instead of `String`
- Csproj file NoWarn: during building don't throw warnings for missing or improper XML documentations: `CS1591` and  `CS1570`
- Bumped NuGet package versions
- Bumped version to 2.13.0 in the csproj file and in the request header (see `GoCardlessClient.cs` line227, line229)

### CODE REVIEW

**Comment by peterdeme** [comment]
@jasonlafferty

**Comment by danwakefield** [comment]
@peterdeme Sorry for the slow response. We generate our clients using an internal tool that uses json-hyperschema and templates for each language. 

This unfortunately means that we cannot merge the PR here, We will attempt to apply the changes to the internal repo and regenerate and release the client when tests pass but we can't guarantee a timeline since the changes are not critical.

**Comment by peterdeme** [comment]
@danwakefield 
Thanks for the reply.
Well, I have mixed feelings. I do understand that you want to keep your libs standardized but having it opensource is makes less sense if community help is not accepted at all.
While it's not critical, .NET Standard 2.0 was released [1,5 year ago](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/) and we are getting this warning when we add the the NuGet package
image
If my PR is not mergeable in its current form at least please fix the `TargetFrameworks` in the csproj file.

**Comment by danwakefield** [comment]
We will accept your PR, but we currently have to apply it by hand internally. 

I'll try to figure out what the functional changes are and which changes are whitespace / preference etc so we can get the important things released ASAP.

Edit:
Ok, The changes I've pulled internally are

1. Updates of `String` -> `string`
2. Updates to `csproj` files

I've left out:

1. Strong typing of HttpMethod; The internal template is complicated and I'll have to give this some thought
2. The Change to VerifySignature; I don't know DotNet so I can't tell if this could break anything etc. 
3. Removing Joiner; I have no idea if the template builder might use this in the future

I'll let you know once its been reviewed and we release the changes.

**Comment by peterdeme** [comment]
I appreciate the quick turn around, Dan, thank you. My team have few other ideas as well (like incorporating [Polly](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory) instead of using the hacky retry logic, eliminating the need for reflection, or adding ASP.NET Core dependency injection extensions similarly to [this](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs) one), but I guess we won't upstream it if breaks your internal tooling or requires extra effort to merge.
Thanks again for the netstandard version upgrade, though!

**Comment by danwakefield** [comment]
Thanks, I've merged the changes and they should be available soon.

**Comment by peterdeme** [comment]
Thanks Dan!

**Pull request closed without merging**
